name: {{ name }}
version: '3.2'

services:
  db1:
    image: cockroachdb/cockroach:v22.1.6
    container_name: {{ name }}-db1
    hostname: {{ name }}-db1
    ports:
     - 26257:26257
     - 8080:8080
    command: start --insecure --join={{ name }}-db1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 15s
      timeout: 5s
      retries: 2
      start_period: 5s
    networks:
      - {{ name }}
    volumes:
      - db1:/cockroach/cockroach-data

networks:
  {{ name }}:
    name: {{ name }}

volumes:
  db1:
    name: {{ name }}-db1
